---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: inlets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-operator
  template:
    metadata:
      labels:
        app: inlets-operator
      annotations:
        prometheus.io.scrape: 'true'
    spec:
      serviceAccountName: inlets-operator
      containers:
      - name: operator
        image: alexellis/inlets-operator:latest
        imagePullPolicy: Always
        command:
          - ./inlets-operator
          - "-access-key=TOKEN"
          - "-provider=digitalocean"
        env:
        - name: test_env
          value: populate_this
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 25Mi
